name: Channel validator

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: write

concurrency:
  group: 'channel-checking-group'
  cancel-in-progress: false

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'

    
        - name: Install dependencies
          run: pip install beautifulsoup4 requests
        
        - name: Run script
          run: python .github/checker.py
          env: 
            BODY: "${{ github.event.issue.body }}"
        
        - name: Comment on issue
          uses: actions/github-script@v7
          with:
            script: |
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: process.env.body
                })
          env: 
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

        - name: Commit changes
          run: |
            USERNAME="${{github.event.issue.user.login}}"
            USER_EMAIL="${{github.event.issue.user.login}}@users.noreply.github.com"
          
            git add channels.txt

            if git diff --cached --quiet; then
              echo "No changes to commit."
            else
              git commit --author $USERNAME <$USER_EMAIL> -m "Update channels.txt"
              git push
            fi
      


        - name: Close the issue
          uses: actions/github-script@v6
          with:
            script: |
                github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  state: "closed"
                })
    
        